# This file defines the contenttypes on the website. See the documentation for
# details: http://docs.bolt.cm/content#defining-contenttypes


# Entries can be used for things like 'news' or 'blogpostings'. They have a 'teaser',
# which can be used for a short blurb on listing-pages, allowing visitors to
# click-through to the rest of the entry. It also has fields for an image and an
# optional video.
# A relation is defined to the pages contenttype. This way you can refer to a page
# from your news-item.
# This contenttype defines 'categories' and 'tags' as taxonomies, allowing the
# editor to use both to categorize a specific entry.
# The 'sort' is set to "datepublish DESC", which means that newer entries will
# show above older entries.

news:
    name: Nieuwsberichten
    slug: nieuws-berichten
    singular_name: Nieuws
    singular_slug: nieuws
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image
        intro:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
#    relations:
#        pages:
#          multiple: false
#          order: title
#          label: Select a page
#    taxonomy: [ categories, tags ]
    record_template: news-detail.twig
    listing_template: news-listing.twig
    listing_records: 10
    default_status: publish
    sort: datepublish DESC
    recordsperpage: 10

activity:
    name: Activiteiten
    slug: activiteiten
    singular_name: Activiteit
    singular_slug: activiteit
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        start:
            type: datetime
        end:
            type: datetime
        wholeday:
            type: checkbox
        image:
            type: image
        intro:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
#    relations:
#        pages:
#          multiple: false
#          order: title
#          label: Select a page
#    taxonomy: [ categories, tags ]
    record_template: activity-detail.twig
    listing_template: activity-listing.twig
    listing_records: 10
    default_status: publish
    sort: start ASC
    recordsperpage: 10
    class: Cowb\Content\ActivityContent

board:
    name: Bestuursleden
    slug: bestuur
    singular_name: Bestuurslid
    singular_slug: bestuurslid
    fields:
        name:
            type: text
            class: large
        slug:
            type: slug
            uses: name
        function:
            type: text
        prio:
            type: integer
        image:
            type: image
        body:
            type: html
            height: 300px
#    relations:
#        pages:
#          multiple: false
#          order: title
#          label: Select a page
#    taxonomy: [ categories, tags ]
    record_template: board-detail.twig
    listing_template: board-listing.twig
    listing_records: 30
    default_status: publish
    recordsperpage: 10
    sort: prio ASC

# Pages can be used for the more 'static' pages on your site. Things like
# 'about us', 'contact' or a 'disclaimer'. This content-type has a 'templateselect'
# field, which allows you to override the record_template setting for an
# individual page.
# The taxonomy for this contenttype is defined as 'chapters', which is a so-called
# "grouping" taxonomy. This way you can easily group sets of pages that logically
# belong together. If your site has a 'services' section, in which you'd like to
# list the different types of services a company provides, you can group these
# together.

pages:
    name: Pagina's
    slug: paginas
    singular_name: Pagina
    singular_slug: info
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        description:
            type: textarea
            height: 150px
        body:
            type: html
            height: 300px
#        template:
#            type: templateselect
#            filter: '*.twig'
#    taxonomy: [ chapters ]
    sort: title
    default_status: publish
    recordsperpage: 100

picasa_album:
    name: Foto albums
    slug: foto-albums
    singular_name: Foto album
    singular_slug: foto-album
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        description:
            type: textarea
            height: 150px
        url:
            type: text
        thumb_url:
            type: text
        sync:
            type: checkbox
    sort: datepublish DESC
    record_template: picasa-detail.twig
    listing_template: picasa-listing.twig
    default_status: draft
    recordsperpage: 100

picasa_photo:
    name: Foto's
    slug: fotos
    singular_name: Foto
    singular_slug: foto
    show_on_dashboard: false
    fields:
        album_id:
            type: integer
        title:
            type: text
            class: large
        url:
            type: text
        thumb_url:
            type: text
    sort: datepublish ASC
    default_status: published
    recordsperpage: 1000

# possible field types:
# text - varchar(256) - input type text.
# integer - integer - Input field for integer numbers.
# float - double - Input field for floating numbers, stored as 'Double'.
# geolocation - text (65kb) - Input field for geolocation. Enter an address, and the location is geocoded to latitude/longitude coordinates
# imagelist - text (65kb) - Input type for imagelists. Add multiple images with a description. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# filelist - text (65kb) - Input type for a list of files. Including a description.
# video - varchar(256) - Video embed widget, stored as filename.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# markdown - varchar(32768) - Simple, plain < textarea > field, which is parsed as Markdown text.
# datetime - datetime - date and time selector widget.
# date - datetime - date selector widget.
# select - varchar(256) - select with predefined values
# templateselect - varchar(256) - select with template filenames
# checkbox - integer - checkbox-field which is 1 (checked) or 0 (unchecked)